apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-y8da
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0021-tenant/tkrw-pr712-0075-0021-app/devfile-sample-y8da@sha256:1ee4ad28fd92844e3013c3d27ce7925779604cad96a4a9490ad755728f76f68f
        name: my-nodejs
        resources: {}
status: {}
